/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package org.openmobster.titanium.module;

import java.util.Vector;

import android.app.Activity;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import org.openmobster.core.mobileCloud.android_native.framework.CloudService;
import org.openmobster.core.mobileCloud.android_native.framework.ViewHelper;
import org.openmobster.core.mobileCloud.api.ui.framework.AppConfig;

@Kroll.module(name="TitaniumModule", id="org.openmobster.titanium.module")
public class TitaniumModuleModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TitaniumModuleModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TitaniumModuleModule(TiContext tiContext) 
	{
		super(tiContext);
		
		//Bootstrap the Cloud Service
		Activity activity = tiContext.getActivity();
		try
		{	
			CloudService.getInstance().start(activity);
		}
		catch(Throwable t)
		{
			ViewHelper.getOkModalWithCloseApp(activity, "System Error", "CloudManager App is either not installed or not running").
			show();
		}
	}

	// Methods
	@Kroll.method
	public String example() 
	{
		Log.d(LCAT, "example called");
		return "hello world";
	}
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp() 
	{
		Log.d(LCAT, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) 
	{
		Log.d(LCAT, "set example property: " + value);
	}

}
